### PR TITLE
Check mandatory fields for latest item

### PR DESCRIPTION
**Pull request by gidsg**
Adding a test that mandatory fields should be visible on the newest item. To catch the case where either we remove a mandatory field or it starts coming back as empty. I am also checking there is at least 1 tag on that item and that tag contains mandatory fields. If anyone in @guardian/content-platforms knows any more fields which are mandatory do say and I can add them to the list.

### CODE REVIEW

**Comment by maxharlow** [comment]
Everything inside 'fields' is meant to be optional

**Comment by gidsg** [comment]
OK cool, I thought headline was mandatory since R2 Admin seems to enforce it, but I will take that out.

**Comment by gidsg** [comment]
@maxharlow do you think this looks OK now with that change?

**Comment by gidsg** [comment]
Sorry to bug but could someone from @guardian/content-platforms review this before it bit-rots again? Thanks

**Comment by mchv** [comment]
:+1:

**Pull request merged**
