### PR TITLE
Fix snyk high vuln in akka-http-core (moving from akka to pekko)

### PR DESCRIPTION
**Pull request by Divs-B**
## What does this change?

To fix high vuln in `com.typesafe.play:play-akka-http-server_2.13@2.8.21`:
- we have upgraded play to version 3.
- made changes to code required for moving from akka to pekko.

Co-authored by @jonathonherbert 

## How to test

By running `snyk test`
And I think need to deploy on PROD and need to monitor logs

## How can we measure success?

No high vuln in the termnal when `snyk test`
And if deployed, logs should not report any errors

### CODE REVIEW

**Comment by codingWithRach** [comment]
Forgive my lack of knowledge, but can we (should we?) replace akka with pekko?

**Review by codingWithRach — APPROVED** [review]
Looks good (subject to monitoring on PROD), but maybe need to update the PR description to reflect the change from akka to pekko

**Comment by Divs-B** [comment]
Thanks @codingWithRach for approving and also for mentioning akka to pekko change which co-incidentally @jonathonherbert and I paired on the same time to get it done.
PR description is also edited.

Will merge and deploy on PROD and monitor the logs 👍

**Comment by Divs-B** [comment]
Deployed at 12.45pm: 

image

Logs working fine:

image

**Pull request merged**
